flowchart TB
    user[Usuários / Clientes] --> r53[Route 53]
    r53 --> waf[AWS WAF]
    waf --> albprod[ALB Production]

    qa[QA / Time Dev] --> albstg[ALB Staging]

    subgraph git[Repositórios Git]
        apprepo[app-api]
        gitops[platform-gitops<br>staging + production]
        infra[platform-infra<br>Terraform]
    end

    subgraph cicd[CI/CD]
        pipeline[Pipeline<br>Build/Test/Scan]
        trivy[Trivy/Grype]
        sbom[SBOM]
        cosign[Cosign<br>Assinatura]
    end

    subgraph shared[Shared Services Account]
        ecr[ECR<br>Imagens versionadas e assinadas]
        obs[Observabilidade Central<br>CloudWatch/Prometheus/Grafana]
        secretsShared[Secrets Manager<br>opcional compartilhado]
    end

    subgraph staging[AWS Account - Staging]
        subgraph vpcstg[VPC Staging multi-AZ]
            subgraph pubstg[Subnets públicas]
                albstg
            end
            subgraph privstg[Subnets privadas]
                subgraph eksstg[EKS Staging]
                    fluxstg[FluxCD Staging]
                    ingstg[Ingress]
                    svcstg[Service]
                    podstg[Pods API Staging]
                    esostg[External Secrets]
                    kyvstg[Kyverno]
                end
            end
        end
        secstg[Secrets Manager Staging]
    end

    subgraph production[AWS Account - Production]
        subgraph vpcprod[VPC Production multi-AZ]
            subgraph pubprod[Subnets públicas]
                albprod
            end
            subgraph privprod[Subnets privadas]
                subgraph eksprod[EKS Production]
                    fluxprod[FluxCD Production]
                    ingprod[Ingress]
                    svcprod[Service]
                    podsprod[Pods API Production]
                    esoprod[External Secrets]
                    kyvprod[Kyverno]
                end
            end
        end
        secprod[Secrets Manager Production]
    end

    apprepo --> pipeline
    pipeline --> trivy --> sbom
    pipeline --> ecr
    pipeline --> cosign --> ecr
    pipeline --> gitops

    gitops --> fluxstg
    gitops --> fluxprod

    albstg --> ingstg --> svcstg --> podstg
    albprod --> ingprod --> svcprod --> podsprod

    esostg --> secstg
    esoprod --> secprod

    podstg --> obs
    podsprod --> obs

    infra --> staging
    infra --> production
    infra --> shared